<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import

class bkex extends Exchange {

    public function describe () {
        return array_replace_recursive (parent::describe (), array (
            'id' => 'bkex',
            'name' => 'BKEX',
            'countries' => ['BVI'],
            'version' => 'v1',
            'rateLimit' => 1000,
            'has' => array (
                'createMarketOrder' => false,
                'fetchOrder' => true,
                'fetchOrders' => true,
                'fetchOpenOrders' => true,
                'fetchCurrencies' => false,
                'fetchTicker' => true,
                'fetchTickers' => false,
                'fetchOHLCV' => false,
                'fetchOrderBook' => true,
                'fetchTrades' => false,
            ),
            'urls' => array (
                'api' => array (
                    'public' => 'https://api.bkex.com/v1',
                    'private' => 'https://api.bkex.com/v1/u',
                ),
                'www' => 'https://www.bkex.com',
                'doc' => array (
                    'https://github.com/bkexexchange/bkex-official-api-docs/blob/master/api_EN.md',
                ),
                'fees' => 'https://www.bkex.com/help/instruction/33',
            ),
            'api' => array (
                'public' => array (
                    'get' => array (
                        'exchangeInfo',
                        'q/depth',
                        'q/deals',
                        'q/ticker',
                        'q/ticker/price',
                        'q/kline',
                    ),
                ),
                'private' => array (
                    'get' => array (
                        'trade/order/listUnfinished',
                        'trade/order/history',
                        'trade/order/unfinished/detail',
                        'trade/order/finished/detail',
                        'wallet/balance',
                        'wallet/address',
                        'wallet/withdraw',
                        'wallet/depositRecord',
                        'wallet/withdrawRecord',
                    ),
                    'post' => array (
                        'trade/order/create',
                        'trade/order/cancel',
                        'trade/order/batchCreate',
                    ),
                ),
            ),
            'fees' => array (
                'trading' => array (
                    'maker' => 0.09,
                    'taker' => 0.12,
                ),
            ),
        ));
    }

    public function fetch_markets ($params = array ()) {
        $response = $this->publicGetExchangeInfo ($params);
        $data = $this->safe_value($response, 'data');
        $markets = $this->safe_value($data, 'pairs');
        $numMarkets = is_array ($markets) ? count ($markets) : 0;
        if ($numMarkets < 1) {
            throw new ExchangeError($this->id . ' publicGetExchangeInfo returned empty $response => ' . $this->json ($markets));
        }
        $result = array();
        for ($i = 0; $i < count ($markets); $i++) {
            $market = $markets[$i];
            $id = $this->safe_string($market, 'pair');
            $baseId = explode('_', $id)[0];
            $quoteId = explode('_', $id)[1];
            $base = $this->safe_currency_code($baseId);
            $quote = $this->safe_currency_code($quoteId);
            $symbol = $base . '/' . $quote;
            $precision = array (
                'amount' => $this->safe_integer($market, 'amountPrecision'),
                'price' => $this->safe_integer($market, 'pricePrecision') || $this->safe_integer($market, 'defaultPrecision'),
            );
            $minAmount = $this->safe_float($market, 'minimumTradeAmount');
            $result[] = array (
                'id' => $id,
                'symbol' => $symbol,
                'base' => $base,
                'quote' => $quote,
                'baseId' => $baseId,
                'quoteId' => $quoteId,
                'active' => true,
                'precision' => $precision,
                'limits' => array (
                    'amount' => array (
                        'min' => $minAmount,
                        'max' => null,
                    ),
                    'price' => array (
                        'min' => pow(10, -$precision['price']),
                        'max' => null,
                    ),
                    'cost' => array (
                        'min' => null,
                        'max' => null,
                    ),
                ),
                'info' => $market,
            );
        }
        return $result;
    }

    public function fetch_ticker ($symbol, $params = array ()) {
        $this->load_markets();
        $timestamp = $this->milliseconds ();
        $market = $this->market ($symbol);
        $request = array_merge (array (
            'pair' => $this->safe_string($market, 'id'),
        ), $params);
        $response = $this->publicGetQTicker ($request);
        $ticker = $this->safe_value($response, 'data');
        return array (
            'symbol' => $symbol,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601 ($timestamp),
            'high' => $this->safe_float($ticker, 'h'),
            'low' => $this->safe_float($ticker, 'l'),
            'bid' => null,
            'bidVolume' => null,
            'ask' => null,
            'askVolume' => null,
            'vwap' => null,
            'previousClose' => null,
            'open' => $this->safe_float($ticker, 'o'),
            'close' => $this->safe_float($ticker, 'c'),
            'last' => $this->safe_float($ticker, 'c'),
            'percentage' => null,
            'change' => $this->safe_float($ticker, 'r'),
            'average' => null,
            'baseVolume' => $this->safe_float($ticker, 'a'),
            'quoteVolume' => null,
            'info' => $ticker,
        );
    }

    public function fetch_order_book ($symbol, $limit = null, $params = array ()) {
        $this->load_markets();
        $request = array (
            'pair' => $this->market_id($symbol),
        );
        if ($limit !== null) {
            $request['size'] = $limit;
        }
        $response = $this->publicGetQDepth (array_merge ($request, $params));
        $data = $this->safe_value($response, 'data');
        return $this->parse_order_book($data, null, 'bids', 'asks', 'price', 'amt');
    }

    public function fetch_balance ($params = array ()) {
        $this->load_markets();
        $query = $this->omit ($params, 'type');
        $response = $this->privateGetWalletBalance ($query);
        $balances = $this->safe_value($response, 'data');
        $wallets = $this->safe_value($balances, 'WALLET');
        $result = array( 'info' => $wallets );
        for ($i = 0; $i < count ($wallets); $i++) {
            $wallet = $wallets[$i];
            $currencyId = $wallet['coinType'];
            $code = $this->safe_currency_code($currencyId);
            $account = $this->account ();
            $account['free'] = $this->safe_float($wallet, 'available');
            $account['total'] = $this->safe_float($wallet, 'total');
            $result[$code] = $account;
        }
        return $this->parse_balance($result);
    }

    public function create_order ($symbol, $type, $side, $amount, $price = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market ($symbol);
        $method = 'privatePostTradeOrderCreate';
        $direction = $side === 'buy' ? 'BID' : 'ASK';
        $request = array (
            'amount' => $this->amount_to_precision($symbol, $amount),
            'direction' => $direction,
            'pair' => $this->safe_string($market, 'id'),
            'price' => $this->price_to_precision($symbol, $price),
        );
        $response = $this->$method (array_merge ($request, $params));
        return array (
            'id' => $this->safe_value($response, 'data'),
            'info' => $response,
        );
    }

    public function cancel_order ($id, $symbol = null, $params = array ()) {
        $this->load_markets();
        $request = array (
            'orderNo' => $id,
            'pair' => $this->market_id($symbol),
        );
        return $this->privatePostTradeOrderCancel (array_merge ($request, $params));
    }

    public function fetch_open_orders ($symbol = null, $since = null, $limit = null, $params = array ()) {
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' fetchOrders requires a $symbol argument');
        }
        $this->load_markets();
        $market = $this->market ($symbol);
        $request = array (
            'pair' => $this->safe_string($market, 'id'),
        );
        if ($limit !== null) {
            $request['size'] = $limit;
        }
        $response = $this->privateGetTradeOrderListUnfinished (array_merge ($request, $params));
        $result = $this->safe_value($response, 'data');
        return $this->parse_orders($this->safe_value($result, 'data'), $market, $since, $limit);
    }

    public function fetch_order ($id, $symbol = null, $params = array ()) {
        $this->load_markets();
        $request = array (
            'orderNo' => $id,
            'pair' => $this->market_id($symbol),
        );
        $response = $this->privateGetTradeOrderUnfinishedDetail (array_merge ($request, $params));
        $data = $this->safe_value($response, 'data');
        if (!$data) {
            throw new OrderNotFound($this->id . ' order ' . $id . ' not found');
        }
        return $this->parse_order($data);
    }

    public function parse_order ($order, $market = null) {
        $marketName = $this->safe_string($order, 'pair');
        $market = $market || $this->find_market($marketName);
        $timestamp = $this->safe_string($order, 'createdTime');
        if ($timestamp !== null) {
            $timestamp = (int) round(floatval ($timestamp) * 1000);
        }
        $direction = $this->safe_value($order, 'direction');
        $side = $direction === 'BID' ? 'BUY' : 'SELL';
        $amount = $this->safe_float($order, 'totalAmount');
        $fillAmount = $this->safe_float($order, 'dealAmount', $amount);
        $remaining = $amount - $fillAmount;
        return array (
            'id' => $this->safe_string($order, 'id'),
            'datetime' => $this->iso8601 ($timestamp),
            'timestamp' => $timestamp,
            'lastTradeTimestamp' => null,
            'status' => null,
            'symbol' => $this->safe_string($market, 'symbol'),
            'side' => $side,
            'type' => $this->safe_string($order, 'orderType'),
            'price' => $this->safe_float($order, 'price'),
            'cost' => null,
            'amount' => $amount,
            'filled' => $fillAmount,
            'remaining' => $remaining,
            'fee' => null,
            'info' => $order,
        );
    }

    public function sign ($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->urls['api'][$api] . '/' . $this->implode_params($path, $params);
        $query = $this->omit ($params, $this->extract_params($path));
        if ($method === 'GET') {
            if ($query) {
                $url .= '?' . $this->urlencode ($query);
            }
        }
        if ($api === 'private') {
            $this->check_required_credentials();
            $query = $this->urlencode ($query);
            if ($method === 'POST') {
                $body = $query;
            }
            $secret = $this->encode ($this->secret);
            $signature = $this->hmac ($query, $secret, 'sha256');
            $headers = array (
                'Cache-Control' => 'no-cache',
                'Content-type' => 'application/x-www-form-urlencoded',
                'X_ACCESS_KEY' => $this->apiKey,
                'X_SIGNATURE' => $signature,
            );
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function handle_errors ($code, $reason, $url, $method, $headers, $body, $response, $requestHeaders, $requestBody) {
        $httpCode = $this->safe_integer($response, 'code', 200);
        if ($response === null) {
            return;
        }
        if ($code >= 400) {
            throw new ExchangeError($this->id . ' HTTP Error ' . $code . ' $reason => ' . $reason);
        }
        if ($httpCode >= 400) {
            $message = $this->safe_value($response, 'msg', '');
            throw new ExchangeError($this->id . ' HTTP Error ' . $httpCode . ' $message => ' . $message);
        }
    }
}
